### ISSUE TITLE
Publish meta box should be first

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/strong-testimonials#294]
**Describe the bug**
Publish meta box should be first and only after that should the upsell pe present.

**To Reproduce**
1. Go and edit a testimonial

**Screenshots**
![image](https://user-images.githubusercontent.com/44024114/150967510-8a0d0f75-08c5-4b6b-95fd-edbca2e7892a.png)

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Strong Testimonials version: 
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:
